In [87]:
import numpy as np

In [88]:
j=np.array([[4,6],[2,1]])

In [89]:
j

array([[4, 6],
       [2, 1]])

In [91]:

p=np.sort(j,axis=0)
p


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [4., 5., 6., 8.]])

In [92]:

np.sort(p,axis=1)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [4., 5., 6., 8.]])

In [93]:

first_names=np.array(["Betsey", "Shelley", "Lanell", "Genesis", "Margery"])

last_names=np.array(["Battle","Brein","Plotner","Stahl","Woolum"])

dtype=[("first","U10"),("last","U10")]

j=np.array(list(zip(first_names,last_names)),dtype=dtype)

j


array([('Betsey', 'Battle'), ('Shelley', 'Brein'), ('Lanell', 'Plotner'),
       ('Genesis', 'Stahl'), ('Margery', 'Woolum')],
      dtype=[('first', '<U10'), ('last', '<U10')])

In [94]:

np.argsort(j,order=["last","first"])


array([0, 1, 2, 3, 4])

In [95]:
h=np.array([[0,10,20,30,40]])

h

h.ndim

k=h>10
k

r=h[k]

r

array([20, 30, 40])

In [96]:
np.where(k)

hf=np.array([5,7,5,8,6,8,2])
np.save("nupu",hf)
np.savetxt("nupi",hf)

n=np.zeros((4,4))

n.size*n.itemsize

128

In [97]:

p=np.array([[10,20,30,40,50]])

l=p.flat

for i in l:
    print(i)
    

10
20
30
40
50


In [98]:

np.full((3,5),2,dtype="uint")


array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint64)

In [99]:

np.ones((3,5),dtype="uint")*2


array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=uint64)

In [100]:

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
j=np.eye(4)

j

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
np.fill_diagonal(j,(4,5,6,8))

print(j)

[[4. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]


In [103]:
l=np.arange(4,dtype="int64")

l=l*0


In [104]:
l

array([0, 0, 0, 0])

In [105]:
l=l+10

In [106]:
l

array([10, 10, 10, 10])

In [107]:
k=np.full((4),10,dtype="int64")
k


array([10, 10, 10, 10])

In [ ]:
\