## Sorting Arrays 

In [2]:
import numpy as np

In [3]:
arr=np.array(['banana','almond','chocolate'])

In [5]:
print(np.sort(arr))

['almond' 'banana' 'chocolate']


In [6]:
ar=np.array([False,True,True,False,True])

In [7]:
print(np.sort(ar))

[False False  True  True  True]


In [8]:
# Let's  see the  sorting in the  2d array 

In [9]:
arr2=np.array([[3,2,1,],[4,5,8]])

In [10]:
print(np.sort(arr2))

[[1 2 3]
 [4 5 8]]


## Iteration

In [12]:
# if  we  have  iterate  to  the  elements  of the  array 
# we use the  for loops

# see,

In [13]:
arr1=np.array([1,2,3,4,5,6,7,8,9])

In [14]:
for x in arr1:
    print(x)

1
2
3
4
5
6
7
8
9


In [17]:
arr2=np.array([[1,2,3,4],[5,6,7,9]])

In [18]:
for x in arr2:
    print(x)

[1 2 3 4]
[5 6 7 9]


In [20]:
# same for  3d one
arr3=np.array([[[2,5,8,9],[11,24,48,58]],[[54,78,14,26],[1,4,7,8]]])

In [22]:
for x in arr3:
    print(x)

[[ 2  5  8  9]
 [11 24 48 58]]
[[54 78 14 26]
 [ 1  4  7  8]]


In [23]:
# if we  have  to  iterate  down to  the  scalar unit in nd array then we have to use 
# the nested loop here

In [24]:
for x in arr2:
    for y  in x:
        print(y)

1
2
3
4
5
6
7
9


In [25]:
for x in arr3:
    for y in x:
        for z in y:
            print(z)

2
5
8
9
11
24
48
58
54
78
14
26
1
4
7
8


In [28]:
arr4=np.array([[[[2,5,8,9],[11,24,48,58]],[[54,78,14,26],[1,4,7,8]]],[[[2,5,8,9],[11,24,48,58]],[[54,78,14,26],[1,4,7,8]]]])

In [31]:
for x in arr4:
    for y in x:
        for z in y:
            for a in z:
                print(a)

2
5
8
9
11
24
48
58
54
78
14
26
1
4
7
8
2
5
8
9
11
24
48
58
54
78
14
26
1
4
7
8


In [32]:
# here you  can  see that

In [33]:
# ok but   one  thing  arises in your mind like  if we got big array more than 4d array
# then it will be more difficult to do that  and one thing more  it will become  more 
# system intensive(or requirement increases

In [34]:
# to solve  problem  with high dimensionality we use ---> nditer()

## nditer() method

In [35]:
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
6
7
9


In [38]:
# let's go  with  3d array

In [40]:
for x in np.nditer(arr3[:,::2]):
    print(x)

2
5
8
9
54
78
14
26


## Searching

In [48]:
a=np.array([1,2,4,5,6,7,2,8,9])

In [49]:
x=np.where(a==2)

In [51]:
print(x)

(array([1, 6]),)


In [52]:
# one  thing we  can  do more  like if  we want  to  have only even  numbers

In [53]:
ev=np.where(a%2==0)

In [55]:
print(ev) # it returns indexes where the value are even

(array([1, 2, 4, 6, 7]),)


In [57]:
od=np.where(a%2!=0)

In [58]:
od

(array([0, 3, 5, 8]),)

## Search Sorted:

#### •Searchsorted() method performs binary search in array
#### •Returns the index at which specified value should be present to maintain order
#### •Assumes the array

In [60]:
# so we need just  sorted  array to do so

In [61]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [62]:
x=np.searchsorted(arr,7)

In [63]:
x

6

In [68]:
# i f  we  search  any element  which is not been in the array then it will retuurn 
# the  value equal to the size of the  array  indicating it is  not been  available

In [69]:
np.searchsorted(arr,120)

9

In [70]:
s=np.searchsorted(arr,[4,9])

In [71]:
s # show index where these values are availablel

array([3, 8])

In [72]:
# Always  remembered  you can   only use searchsorted if the array is sorted 

In [73]:
x=np.array([1,3,2,1,2,5,32,56,21,67])

In [74]:
x_=np.sort(x)

In [75]:
x_

array([ 1,  1,  2,  2,  3,  5, 21, 32, 56, 67])

In [76]:
ss=np.searchsorted(x_,2)

In [77]:
ss

2