In [1]:
import numpy  as np

In [2]:
s=np.array([[1,2,4],[8,2,2]])

In [3]:
s

array([[1, 2, 4],
       [8, 2, 2]])

In [4]:
s1=np.arange(0,10)

In [5]:
s1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
l=np.zeros((3,3))
l

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
l1=np.ones((3,3))
l1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
e=np.eye(3,3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(10)

array([0.55571504, 0.48002805, 0.88972922, 0.5968825 , 0.73011148,
       0.19904047, 0.38721343, 0.39172245, 0.50025399, 0.16746142])

In [10]:
np.random.rand(10,50,10)

array([[[0.11663757, 0.44338515, 0.12053299, ..., 0.95686844,
         0.96893202, 0.57021863],
        [0.7025268 , 0.7262988 , 0.59690043, ..., 0.24274521,
         0.90831044, 0.83625452],
        [0.37723865, 0.79538003, 0.66396358, ..., 0.35869377,
         0.68350104, 0.08935999],
        ...,
        [0.79462136, 0.43402738, 0.38063308, ..., 0.63999429,
         0.90817993, 0.43575375],
        [0.64779476, 0.6768981 , 0.17961435, ..., 0.24280135,
         0.82846848, 0.74457475],
        [0.84919833, 0.79094769, 0.89331923, ..., 0.7839886 ,
         0.27351749, 0.80599804]],

       [[0.12264408, 0.53255215, 0.08312659, ..., 0.41008041,
         0.57597388, 0.14162587],
        [0.38645945, 0.41780946, 0.92257347, ..., 0.15634296,
         0.58148715, 0.55616774],
        [0.79384896, 0.037779  , 0.2007238 , ..., 0.45772319,
         0.25834808, 0.88292378],
        ...,
        [0.32536305, 0.04606672, 0.15282872, ..., 0.02368216,
         0.93220779, 0.83990401],
        [0.2

In [11]:
j=np.linspace(0,5,20)

In [12]:
j

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [13]:
h=np.arange(1,5).reshape(2,2)

In [14]:
h

array([[1, 2],
       [3, 4]])

In [15]:
k=np.random.rand(3,3,3)

In [16]:
k

array([[[0.18375891, 0.55150246, 0.59425563],
        [0.52120274, 0.35566933, 0.61621224],
        [0.4720135 , 0.08938683, 0.62509401]],

       [[0.38403132, 0.81976566, 0.19769228],
        [0.08725766, 0.3875342 , 0.94003452],
        [0.03633841, 0.14341394, 0.76040289]],

       [[0.32856714, 0.67116428, 0.87413699],
        [0.63159801, 0.83131931, 0.2096439 ],
        [0.62438667, 0.82558105, 0.2019703 ]]])

In [17]:
#  matrix  of 5X5  with 1. 2 3 4....25

s=np.arange(1,26).reshape(5,5)

In [18]:
s

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
h=np.arange(0,20,2)

In [20]:
h

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
h.size

10

In [22]:
h1=np.arange(1,21,2)

In [23]:
h1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
h1.size

10

In [25]:
k=np.array([1,2,3,4,5])

k1=k[::-1]

In [26]:
k1

array([5, 4, 3, 2, 1])

In [27]:
g=np.arange(0,10).reshape(2,5)

In [28]:
g1=np.mean(g)

In [29]:
g1

4.5

In [30]:
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
w=np.random.randint(0,10,size=(2,5))

mn=np.mean(w)

In [32]:
w

array([[6, 6, 3, 7, 4],
       [6, 1, 4, 8, 0]])

In [33]:
mn

4.5

In [34]:
# so  i didn't  read the question clearly  it  was talking about the
# generating the random integer between the 0 amd 10 and them  find the mean 
# of the 

In [35]:
# we have to extract the   element from the array  which  are greater than 
# 5

In [36]:
l=w[w>5]

In [37]:
l

array([6, 6, 7, 6, 8])

In [38]:
# create the  4X4 matrix  and  swap fist and last row

h=np.arange(16,32).reshape(4,4)

In [39]:
h

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [40]:
temp=h[0].copy()
h[0]=h[-1]
h[-1]=temp

In [41]:
h

array([[28, 29, 30, 31],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [16, 17, 18, 19]])

In [42]:
# Multiply  a  5X3 matrx  with 3X2 matrix

g=np.arange(15).reshape(5,3)
j=np.random.rand(3,2)

In [43]:
g=np.matrix(g)
j=np.matrix(j)

print(g)
print()
print(j)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

[[0.10041405 0.23551385]
 [0.47679655 0.40858775]
 [0.30151517 0.22766274]]


In [44]:
f=g*j

In [45]:
f

matrix([[ 1.07982689,  0.86391322],
        [ 3.71600422,  3.47920622],
        [ 6.35218154,  6.09449922],
        [ 8.98835886,  8.70979222],
        [11.62453618, 11.32508522]])

In [46]:
g=np.arange(12,36).reshape(2,4,3)

In [47]:
k=np.arange(1,13)

In [48]:
k.shape

(12,)

In [49]:
s=np.random.randint(0,8,size=(3,3))

In [50]:
s

array([[5, 5, 3],
       [5, 6, 2],
       [0, 2, 6]])

In [51]:
s=np.matrix(s)

In [52]:
s

matrix([[5, 5, 3],
        [5, 6, 2],
        [0, 2, 6]])

In [53]:
d=np.arange(0,9).reshape(3,3)

In [54]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
d.sum()

36

In [56]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [57]:
row_sum=np.sum(matrix,axis=0)

In [58]:
col_sum=np.sum(matrix,axis=1)

In [59]:
row_sum

array([12, 15, 18])

In [60]:
col_sum


array([ 6, 15, 24])

In [61]:
vector=np.random.rand(10)

In [62]:
vector.size

10

In [63]:
d=np.linspace(0,1,10,endpoint=False)

In [64]:
d

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [65]:
k=np.dot(s,j)

In [66]:
k

matrix([[3.79059853, 3.9034962 ],
        [3.96587991, 4.08442121],
        [2.76268413, 2.18315191]])

In [67]:
s

matrix([[5, 5, 3],
        [5, 6, 2],
        [0, 2, 6]])

In [68]:
j

matrix([[0.10041405, 0.23551385],
        [0.47679655, 0.40858775],
        [0.30151517, 0.22766274]])

In [69]:
eigenvalues,eigenvectors=np.linalg.eig(s)

In [70]:
eigenvalues


array([11.45659255,  0.72453446,  4.81887299])

In [71]:
eigenvectors

matrix([[ 0.66357506, -0.64532889, -0.21886208],
        [ 0.70241371,  0.71429577, -0.49618035],
        [ 0.25745507, -0.27079914,  0.8401812 ]])

In [72]:
a,ind=np.unique(s,return_index=True,axis=0)

In [73]:
a

array([[0, 2, 6],
       [5, 5, 3],
       [5, 6, 2]])

In [74]:
a[ind]

array([[5, 6, 2],
       [0, 2, 6],
       [5, 5, 3]])

In [75]:
ind

array([2, 0, 1])

In [76]:
a = np.array([1, 2, 6, 4, 2, 3, 2])

In [77]:
u,indice=np.unique(a,return_inverse=True)

In [78]:
u

array([1, 2, 3, 4, 6])

In [79]:
indice

array([0, 1, 4, 3, 1, 2, 1])

In [80]:
u[indice]

array([1, 2, 6, 4, 2, 3, 2])

In [81]:
a

array([1, 2, 6, 4, 2, 3, 2])

In [82]:
val,count=np.unique(a,return_counts=True)

print(val)
print(count)


[1 2 3 4 6]
[1 3 1 1 1]


In [83]:
# so we see here it is given here it return indices  with elements which is ampunt
# f the  time  that element comes in the array

In [84]:
val[count]

array([2, 4, 2, 2, 2])

In [85]:
p=np.arange(16,32).reshape(4,4)

In [86]:
p

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [87]:
p.max(axis=1)

array([19, 23, 27, 31])

In [88]:
s=np.array([[4,5,6,8],[4,6,3,9]])
s1=np.array([[9,14,7,8],[4,8,24,9]])

np.intersect1d(s,s1)

array([4, 8, 9])

In [89]:
k=np.random.randint(5,10,size=(2,3))

In [90]:
k=k.astype('float16')

In [91]:
k

array([[7., 7., 7.],
       [5., 6., 7.]], dtype=float16)

In [92]:
h=np.zeros((5,5))

In [93]:
h

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [94]:
h[0,:]=1
h[-1,:]=1
h[:,0]=1
h[:,-1]=1

In [95]:
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
d=np.arange(1,26).reshape(5,5)

In [97]:
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
m=np.mean(d,axis=0)

In [99]:
m

array([11., 12., 13., 14., 15.])

In [100]:
d-m

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [101]:
h=np.random.rand(16).reshape(4,4)
h

array([[0.14371501, 0.92113868, 0.2056218 , 0.45788929],
       [0.2615911 , 0.79308998, 0.75961559, 0.45886252],
       [0.4468927 , 0.95452255, 0.38399153, 0.58606229],
       [0.67682308, 0.56028447, 0.72759219, 0.8583921 ]])

In [102]:
colu_max=np.max(h,axis=0)

In [103]:
colu_max

array([0.67682308, 0.95452255, 0.75961559, 0.8583921 ])

In [104]:
row_max=np.max(h,axis=1)

In [105]:
row_max

array([0.92113868, 0.79308998, 0.95452255, 0.8583921 ])

In [106]:
o=s*s1

In [107]:
s

array([[4, 5, 6, 8],
       [4, 6, 3, 9]])

In [108]:
s1

array([[ 9, 14,  7,  8],
       [ 4,  8, 24,  9]])

In [109]:
o

array([[36, 70, 42, 64],
       [16, 48, 72, 81]])

In [110]:
# we can use arithmetic  operation with their named functions
ko=np.multiply(s,s1)

In [111]:
ko

array([[36, 70, 42, 64],
       [16, 48, 72, 81]])

In [112]:
g=np.matrix(s)
g1=np.matrix(s1)

In [113]:
g1=g1.reshape(4,2)

In [114]:
g*g1

matrix([[287, 216],
        [306, 209]])

In [115]:
h=np.random.rand(3,3)

h

array([[0.07366102, 0.91578532, 0.59855511],
       [0.21452255, 0.71054638, 0.4869552 ],
       [0.43646516, 0.07832915, 0.70460137]])

In [116]:
h.transpose()

array([[0.07366102, 0.21452255, 0.43646516],
       [0.91578532, 0.71054638, 0.07832915],
       [0.59855511, 0.4869552 , 0.70460137]])

In [117]:
inverse_matrix=np.linalg.inv(h)

In [118]:
inverse_matrix

array([[-5.42303614,  7.01614738, -0.24207084],
       [-0.71976733,  2.45464374, -1.08498385],
       [ 3.43931362, -4.61902881,  1.68980844]])

In [119]:
q=np.array([[2,4,5],[7,4,1]])
q1=np.array([[3,4,8],[6,4,8]])

In [120]:
i=np.concatenate((q,q1),axis=1)

In [121]:
i

array([[2, 4, 5, 3, 4, 8],
       [7, 4, 1, 6, 4, 8]])

In [122]:
V=np.vstack((q,q1))

In [123]:
V

array([[2, 4, 5],
       [7, 4, 1],
       [3, 4, 8],
       [6, 4, 8]])

In [124]:
H=np.hstack((q,q1))

In [125]:
H

array([[2, 4, 5, 3, 4, 8],
       [7, 4, 1, 6, 4, 8]])

In [126]:
q

array([[2, 4, 5],
       [7, 4, 1]])

In [127]:
q.ndim

2

In [128]:
qush=np.array([[2,4,5],[7,5,3],[9,12,1],[7,4,1]])
qush

array([[ 2,  4,  5],
       [ 7,  5,  3],
       [ 9, 12,  1],
       [ 7,  4,  1]])

In [129]:
lok=np.zeros_like(qush)

In [130]:
lok[0,:]=1
lok[-1,:]=1
lok[:,0]=1
lok[:,-1]=1

In [131]:
lok

array([[1, 1, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [132]:
qush
qush.shape

(4, 3)

In [133]:
l=8
d=np.where( qush>8,l,qush)

In [134]:
d

array([[2, 4, 5],
       [7, 5, 3],
       [8, 8, 1],
       [7, 4, 1]])

In [135]:
# Vectorization  power

import numpy as np
import time

# Create a large matrix
qush = np.random.randint(1, 20, size=(1000, 1000))
l = 15

# Using np.where
start_time = time.time()
d = np.where(qush > l, l, qush)
print("Time taken using np.where:", time.time() - start_time)

# Using loops
start_time = time.time()
for i in range(qush.shape[0]):
    for j in range(qush.shape[1]):
        if qush[i, j] > l:
            qush[i, j] = l
print("Time taken using loops:", time.time() - start_time)


Time taken using np.where: 0.028211116790771484


Time taken using loops: 1.9657707214355469


In [136]:
k=np.random.randint(16,32,size=(3,3))

In [137]:
k

array([[27, 28, 28],
       [24, 21, 27],
       [29, 20, 31]])

In [138]:
f=np.linalg.det(k)

In [139]:
f

477.00000000000017

In [140]:
trace=np.diagonal(k,offset=0)

In [141]:
np.__version__

'1.26.4'

In [142]:
np.sum(trace)

79

In [143]:
#  the trace f the  matrix is the sum of the diagonal okay

In [144]:
s=np.random.rand(10,10)

In [145]:
s

array([[0.16320375, 0.63334772, 0.49604687, 0.36035197, 0.92529702,
        0.85544222, 0.37216273, 0.46174329, 0.80913525, 0.6050387 ],
       [0.05589441, 0.20286242, 0.30066824, 0.29131891, 0.448332  ,
        0.63856319, 0.7538259 , 0.31817208, 0.38584581, 0.9945594 ],
       [0.26580959, 0.82283375, 0.9634514 , 0.47092405, 0.78672318,
        0.25211016, 0.08210838, 0.05893634, 0.1665763 , 0.95896158],
       [0.40138721, 0.37576464, 0.62538406, 0.70507295, 0.7358098 ,
        0.17848867, 0.90183998, 0.03879916, 0.97177851, 0.44491601],
       [0.91313285, 0.46249435, 0.96491794, 0.2767512 , 0.18963302,
        0.53624966, 0.08438077, 0.85252376, 0.49800572, 0.84306659],
       [0.1604038 , 0.40486464, 0.03470045, 0.43759154, 0.66987057,
        0.25084505, 0.17408617, 0.46939761, 0.27709287, 0.3929991 ],
       [0.3430832 , 0.35653711, 0.48674406, 0.31330694, 0.94820338,
        0.76014813, 0.14576222, 0.21373478, 0.23330268, 0.3968414 ],
       [0.24273874, 0.56392769, 0.3856016

In [146]:
np.argmax(s)

19

In [147]:
ind = np.unravel_index(np.argmax(s, axis=None), s.shape)


In [148]:
ind

(1, 9)

In [149]:
f=np.arange(30)

In [150]:
f.mean()

14.5

In [151]:
v=np.random.randint(0,35,size=30)

In [152]:
v

array([ 1, 28, 34, 32, 20, 14, 12, 13,  2, 23, 32, 31, 12, 34, 34, 29,  4,
       18, 14, 31, 31,  3, 14, 31, 10, 14, 23, 10,  2, 30])

In [153]:
count=np.bincount(v)
count

array([0, 1, 2, 1, 1, 0, 0, 0, 0, 0, 2, 0, 2, 1, 4, 0, 0, 0, 1, 0, 1, 0,
       0, 2, 0, 0, 0, 0, 1, 1, 1, 4, 2, 0, 3])

In [154]:
most_frequent_ele=np.argmax(count)

In [155]:
most_frequent_ele

14

In [156]:
# Adding new row at the end of the matrix

In [157]:
h=np.random.randint(0,50,size=(3,3))

In [158]:
h

array([[22,  6, 15],
       [41, 35,  3],
       [35,  2, 16]])

In [159]:
# h1=np.random.randint(0,34,size=(3))
h1= np.random.rand(3)

In [160]:
h1

array([0.68515707, 0.26357599, 0.48625259])

In [161]:
n_mat=np.vstack([h,h1])

In [162]:
n_mat

array([[22.        ,  6.        , 15.        ],
       [41.        , 35.        ,  3.        ],
       [35.        ,  2.        , 16.        ],
       [ 0.68515707,  0.26357599,  0.48625259]])

In [163]:
# Adding the new column to the  matrix with random values

In [164]:
# for this   you  have to  stack  these  then only  you  could  do that

In [165]:
h

array([[22,  6, 15],
       [41, 35,  3],
       [35,  2, 16]])

In [166]:
n=np.random.rand(3)
n

array([0.14353221, 0.85036399, 0.51187216])

In [167]:
d=np.column_stack([h,n])

In [168]:
d

array([[22.        ,  6.        , 15.        ,  0.14353221],
       [41.        , 35.        ,  3.        ,  0.85036399],
       [35.        ,  2.        , 16.        ,  0.51187216]])

In [169]:
p=np.random.randint(0,56,size=(5,5))

In [170]:
p

array([[47, 17,  9, 22,  1],
       [51, 13, 12,  6,  9],
       [46, 15,  0, 42,  9],
       [ 6, 49, 26, 39, 48],
       [15, 42, 17, 54, 13]])

In [171]:
g=np.sum(p,axis=1)
print(g)
m=np.argmax(g)
print(m)

[ 96  91 112 168 141]
3


In [172]:
p_=np.delete(p,m,axis=0) # for the deletion of row you must chose the axis=0
p_

array([[47, 17,  9, 22,  1],
       [51, 13, 12,  6,  9],
       [46, 15,  0, 42,  9],
       [15, 42, 17, 54, 13]])

In [173]:
np.sum(p_,axis=1)

array([ 96,  91, 112, 141])

In [174]:
# Create the    3x3  row  and  delete the column  with heighest sum

In [175]:
p

array([[47, 17,  9, 22,  1],
       [51, 13, 12,  6,  9],
       [46, 15,  0, 42,  9],
       [ 6, 49, 26, 39, 48],
       [15, 42, 17, 54, 13]])

In [176]:
o=np.sum(p,axis=0)
o

array([165, 136,  64, 163,  80])

In [177]:
# now get  the  argmax  of the  value from the array
gg=np.argmax(o)
gg

0

In [178]:
k=np.delete(p,gg,axis=1)

In [179]:
k

array([[17,  9, 22,  1],
       [13, 12,  6,  9],
       [15,  0, 42,  9],
       [49, 26, 39, 48],
       [42, 17, 54, 13]])

In [180]:
np.sum(k,axis=0)

array([136,  64, 163,  80])

In [181]:
s1

array([[ 9, 14,  7,  8],
       [ 4,  8, 24,  9]])

In [182]:
np.cumsum(s1)

array([ 9, 23, 30, 38, 42, 50, 74, 83])

In [183]:
np.cumsum(s1,axis=0)

array([[ 9, 14,  7,  8],
       [13, 22, 31, 17]])

In [184]:
# compute the  moving average over the  1d array

In [185]:
b=np.array([2,5,17,9,36,3,4,5,16,12,3,44])

In [186]:
window_size=3

In [187]:
window=np.ones(window_size)/window_size

window

array([0.33333333, 0.33333333, 0.33333333])

In [188]:
moving_average=np.convolve(b,window,mode='valid')

In [189]:
moving_average

array([ 8.        , 10.33333333, 20.66666667, 16.        , 14.33333333,
        4.        ,  8.33333333, 11.        , 10.33333333, 19.66666667])

In [190]:
d2=np.random.randint(10,40,size=(2,2))

In [191]:
d2

array([[23, 18],
       [11, 10]])

In [192]:
np.flip(d2,0)

array([[11, 10],
       [23, 18]])

In [193]:
np.flip(d2,(0,1))

array([[10, 11],
       [18, 23]])

In [194]:
np.flip

<function flip at 0x7f668c188630>

In [195]:
import numpy as np

A = np.arange(8).reshape((2, 2, 2))
print(A)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [196]:
np.flip(A,0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [197]:
np.flip(A,1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [198]:
np.flip(A)

array([[[7, 6],
        [5, 4]],

       [[3, 2],
        [1, 0]]])

In [199]:
np.flip(A, (0, 2))


array([[[5, 4],
        [7, 6]],

       [[1, 0],
        [3, 2]]])

In [200]:
A1 = np.random.randn(3, 4, 5)
result = np.all(np.flip(A1, 2) == A1[:, :, ::-1, ...])
print(result)


True


In [201]:
rotated_A=np.rot90(A)

In [202]:
rotated_A

array([[[2, 3],
        [6, 7]],

       [[0, 1],
        [4, 5]]])

In [203]:
k     

array([[17,  9, 22,  1],
       [13, 12,  6,  9],
       [15,  0, 42,  9],
       [49, 26, 39, 48],
       [42, 17, 54, 13]])

In [204]:
l=np.array([5,8,9,3,5,6,7,5,9])

In [205]:
np.split(l,3)

[array([5, 8, 9]), array([3, 5, 6]), array([7, 5, 9])]

In [206]:
d=np.eye(3,3)

In [207]:
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [208]:
f=np.fill_diagonal(d,5)

In [209]:
d

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [210]:
row,ind=np.diag_indices_from(d)

In [211]:
indices=row,ind

In [212]:
d[indices]=[10,12,6]

In [213]:
d

array([[10.,  0.,  0.],
       [ 0., 12.,  0.],
       [ 0.,  0.,  6.]])

In [214]:
h=np.random.randint(0,20,size=(3,3))

In [215]:
h

array([[ 0, 16,  3],
       [ 9, 18, 11],
       [ 0,  9,  5]])

In [216]:
np.sort(h,-1)

array([[ 0,  3, 16],
       [ 9, 11, 18],
       [ 0,  5,  9]])

In [217]:
sorted_indices=np.argsort(h[:,1])

In [218]:
sorted_matrix=h[sorted_indices]

In [219]:
sorted_matrix

array([[ 0,  9,  5],
       [ 0, 16,  3],
       [ 9, 18, 11]])

In [220]:
j=np.array([])

In [221]:
# create the  numpy  array with first  10 element as a prime number

In [223]:
def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(np.sqrt(n))+1):
        if n%i==0:
            return False
        
    return True


def first_n(n):
    prime=[]
    num=2

    while len(prime)<n:
        if is_prime(num):
            prime.append(num)

        num+=1

    return prime



prime_nu=np.array(first_n(10))



In [224]:
prime_nu

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [233]:
p=np.sqrt(6)
p

2.449489742783178

In [234]:
int(p)

2

In [229]:
for i in range(2,2):
    print('h')

In [236]:
l

array([5, 8, 9, 3, 5, 6, 7, 5, 9])

In [238]:
k

array([[17,  9, 22,  1],
       [13, 12,  6,  9],
       [15,  0, 42,  9],
       [49, 26, 39, 48],
       [42, 17, 54, 13]])

In [239]:
l2=np.array([1,5,9,7,5,3,6,8,5,4])

In [240]:
np.intersect1d(l,l2)

array([3, 5, 6, 7, 8, 9])

In [241]:
s=np.random.rand(10)

In [242]:
s

array([0.14376622, 0.13098348, 0.23639829, 0.43274581, 0.56499046,
       0.52578427, 0.10779464, 0.9532221 , 0.18901627, 0.55325032])

In [243]:
s[np.argmax(s)]=0

In [244]:
s

array([0.14376622, 0.13098348, 0.23639829, 0.43274581, 0.56499046,
       0.52578427, 0.10779464, 0.        , 0.18901627, 0.55325032])

In [245]:
# normalizing

Normalizing a matrix by its maximum value means adjusting the values in the matrix so that they all fall within a range from 0 to 1. This is done by dividing each element in the matrix by the maximum value found in the matrix. This process is useful for scaling the values for various numerical methods and algorithms, ensuring that the data is on a common scale without distorting differences in the ranges of values.

In [246]:
z=np.random.rand(3,3)

In [247]:
z

array([[0.21325567, 0.01693828, 0.08238419],
       [0.78273937, 0.2078574 , 0.83203991],
       [0.5832455 , 0.79620746, 0.01643918]])

In [248]:
m=np.max(z)

In [249]:
z=z/m

In [250]:
z

array([[0.25630462, 0.02035754, 0.09901471],
       [0.94074739, 0.24981663, 1.        ],
       [0.7009826 , 0.95693422, 0.01975768]])

In [260]:
l=np.array([5, 8, 9, 3, 5, 6, 7, 5,13, 9])


In [261]:
l2=np.array([1, 5, 9, 7, 5, 3, 6, 8, 5, 4])

In [262]:
np.dot(l,l2)

373

In [272]:
o=np.random.randint(0,80,size=(2,2))

In [273]:
o1=np.random.randint(0,80,size=(2,3))

In [274]:
np.cross(o,o1)

array([[ 1450,  -700,  -893],
       [ 3822,  -858, -3219]])

In [367]:
ran=np.random.rand(11)

In [368]:
ran

array([0.86446023, 0.42500686, 0.99217528, 0.82899995, 0.52499557,
       0.47452504, 0.85754792, 0.7781347 , 0.17556049, 0.993183  ,
       0.79820231])

In [369]:
second_largest=-np.inf

In [370]:
max_value=np.max(ran)
max_value

0.993182997197079

In [374]:
for  v in ran:
    if v!=max_value and  v>second_largest:
        second_largest=v

In [375]:
second_largest

0.992175277507428

In [376]:
o

array([[14, 29],
       [11, 49]])

In [377]:
o.flatten()

array([14, 29, 11, 49])

In [384]:
for i in o.flat:
    print(i)

14
29
11
49


In [388]:
o.flat[[1,3]]=2

In [389]:
o

array([[14,  2],
       [11,  2]])

In [398]:
matrix_rank_3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])
rank=np.linalg.matrix_rank(matrix_rank_3)
print("Rank  of the matrix is ",rank)
print(matrix_rank_3)

Rank  of the matrix is  3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [399]:
matrix_rank_ = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [5, 7, 9]
])
rank=np.linalg.matrix_rank(matrix_rank_)
print("Rank  of the matrix is ",rank)
print(matrix_rank_)

Rank  of the matrix is  2
[[1 2 3]
 [4 5 6]
 [5 7 9]]


In [400]:
matrix_rank_ = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9]
])
rank=np.linalg.matrix_rank(matrix_rank_)
print("Rank  of the matrix is ",rank)
print(matrix_rank_)

Rank  of the matrix is  1
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [402]:
# Coefficient matrix (rank 3)
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])

# Right-hand side vector
b = np.array([6, 15, 35])

# Solve the linear system Ax = b
x = np.linalg.solve(A, b)
print("Solution (Unique):")
print(x)


Solution (Unique):
[ 11. -19.  11.]


In [403]:
# Coefficient matrix (rank 2)
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [5, 7, 9]
])

# Right-hand side vector that is inconsistent
b = np.array([6, 15, 22])

# Check the rank of the augmented matrix
augmented_matrix = np.column_stack((A, b))
print("Rank of coefficient matrix:", np.linalg.matrix_rank(A))
print("Rank of augmented matrix:", np.linalg.matrix_rank(augmented_matrix))

# Use lstsq to find a solution (will give least-squares solution)
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
print("Least-squares solution (No exact solution):")
print(x)


Rank of coefficient matrix: 2
Rank of augmented matrix: 3
Least-squares solution (No exact solution):
[0.83333333 1.         1.16666667]


In [419]:
d=np.random.randint(4,45,size=(2,2))

In [420]:
d

array([[14, 17],
       [37, 27]])

In [421]:
f=[4,5]

In [422]:
d=np.column_stack([d,f])

In [423]:
d

array([[14, 17,  4],
       [37, 27,  5]])

In [428]:
d_mean_col=np.mean(d,axis=0)

In [429]:
d_mean_col

array([25.5, 22. ,  4.5])

In [430]:
d-d_mean_col

array([[-11.5,  -5. ,  -0.5],
       [ 11.5,   5. ,   0.5]])

In [431]:
d_mean_row=np.mean(d,axis=1)

In [435]:
d_mean_row=d_mean_row.reshape(-1,1)  # this  will  help in   to  correspond  with the rows

In [436]:
result_=d-d_mean_row

In [438]:
result_

array([[  2.33333333,   5.33333333,  -7.66666667],
       [ 14.        ,   4.        , -18.        ]])

In [439]:
d_mean_col

array([25.5, 22. ,  4.5])

In [440]:
d=np.arange(10,22).reshape(4,3)

In [441]:
d

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [448]:
d_=np.array([[0.2, 0.11, 1.2],
            [1.3, 0.4, 1.5],
            [0.6, 0.17, 0.18],
            [0.9, 0.2, 0.21]])

l=np.exp(d_)
l

array([[1.22140276, 1.11627807, 3.32011692],
       [3.66929667, 1.4918247 , 4.48168907],
       [1.8221188 , 1.18530485, 1.19721736],
       [2.45960311, 1.22140276, 1.23367806]])

In [444]:
o=np.exp(d)

In [445]:
o

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07],
       [1.78482301e+08, 4.85165195e+08, 1.31881573e+09]])

In [449]:
w=np.exp2(d)

In [450]:
w

array([[1.024000e+03, 2.048000e+03, 4.096000e+03],
       [8.192000e+03, 1.638400e+04, 3.276800e+04],
       [6.553600e+04, 1.310720e+05, 2.621440e+05],
       [5.242880e+05, 1.048576e+06, 2.097152e+06]])

In [454]:
e=np.log(w)

In [455]:
e

array([[ 6.93147181,  7.62461899,  8.31776617],
       [ 9.01091335,  9.70406053, 10.39720771],
       [11.09035489, 11.78350207, 12.47664925],
       [13.16979643, 13.86294361, 14.55609079]])