In [1]:
import numpy as np

In [2]:
j=np.array([[4,6],[2,1]])

In [3]:
j

array([[4, 6],
       [2, 1]])

In [9]:
p=np.sort(j,axis=0)
p

array([[2, 1],
       [4, 6]])

In [10]:
np.sort(p,axis=1)

array([[1, 2],
       [4, 6]])

In [38]:
first_names=np.array(["Betsey", "Shelley", "Lanell", "Genesis", "Margery"])

In [39]:
last_names=np.array(["Battle","Brein","Plotner","Stahl","Woolum"])

In [40]:
dtype=[("first","U10"),("last","U10")]

In [41]:
j=np.array(list(zip(first_names,last_names)),dtype=dtype)

In [42]:
j

array([('Betsey', 'Battle'), ('Shelley', 'Brein'), ('Lanell', 'Plotner'),
       ('Genesis', 'Stahl'), ('Margery', 'Woolum')],
      dtype=[('first', '<U10'), ('last', '<U10')])

In [44]:
np.argsort(j,order=["last","first"])

array([0, 1, 2, 3, 4])

In [46]:
h=np.array([[0,10,20,30,40]])

In [47]:
h

array([[ 0, 10, 20, 30, 40]])

In [48]:
h.ndim

2

In [58]:
k=h>10
k

array([[False, False,  True,  True,  True]])

In [67]:
r=h[k]

In [68]:
r

array([20, 30, 40])

In [70]:
np.where(k)

(array([0, 0, 0]), array([2, 3, 4]))

In [73]:
hf=np.array([5,7,5,8,6,8,2])
np.save("nupu",hf)
np.savetxt("nupi",hf)

In [74]:
n=np.zeros((4,4))

In [79]:
n.size*n.itemsize

128

In [80]:
p=np.array([[10,20,30,40,50]])

In [93]:
l=p.flat

In [94]:
for i in l:
    print(i)
    

10
20
30
40
50
