In [1]:
import numpy as np

In [2]:
n=np.random.rand(40).reshape(8,5)

In [3]:
n

array([[0.87025493, 0.68287549, 0.88614305, 0.8607226 , 0.51597958],
       [0.35477773, 0.46037308, 0.88735216, 0.01026235, 0.33425966],
       [0.35139093, 0.86761118, 0.49658007, 0.87249379, 0.17361579],
       [0.83981457, 0.33314068, 0.59671533, 0.85261432, 0.99228341],
       [0.56747929, 0.54909246, 0.73328361, 0.10576568, 0.06890995],
       [0.58669119, 0.80607588, 0.05520358, 0.61063983, 0.88525627],
       [0.67380493, 0.91111071, 0.90852639, 0.30331306, 0.10155455],
       [0.28013241, 0.89649132, 0.99457605, 0.34944005, 0.17945375]])

In [4]:
b=np.random.rand(1400).reshape(200,7)

In [5]:
b

array([[0.6778732 , 0.31172236, 0.74680501, ..., 0.21352183, 0.9011146 ,
        0.47517196],
       [0.84335723, 0.53473338, 0.21520741, ..., 0.65867256, 0.92783157,
        0.44857571],
       [0.75161001, 0.09214731, 0.1999283 , ..., 0.34651328, 0.3331998 ,
        0.06573145],
       ...,
       [0.71105014, 0.70196388, 0.75505689, ..., 0.81642561, 0.44429224,
        0.00673568],
       [0.59293748, 0.97194876, 0.01275051, ..., 0.77805637, 0.15702545,
        0.62822931],
       [0.05308002, 0.6352957 , 0.6395776 , ..., 0.51235327, 0.45008809,
        0.63446289]])

In [9]:
np.random.seed(20)

In [11]:
cbrt = np.cbrt(7)

In [12]:
nd=200

In [13]:
p=cbrt*np.random.randn(10,4)+nd

In [14]:
p

array([[201.6908267 , 200.37467631, 200.68394275, 195.51750123],
       [197.92478992, 201.07066048, 201.79714021, 198.1282331 ],
       [200.96238963, 200.77744291, 200.61875865, 199.05613894],
       [198.48492638, 198.38860811, 197.55239946, 200.47003621],
       [199.91545839, 202.99877319, 202.01069857, 200.77735483],
       [199.67739161, 193.89831807, 202.14273593, 202.54951299],
       [199.53450969, 199.7512602 , 199.79145727, 202.97687757],
       [200.24634413, 196.04606934, 198.30611253, 197.88701546],
       [201.78450912, 203.94032834, 198.21152803, 196.91446071],
       [201.0082481 , 197.03285104, 200.63052763, 197.82590294]])

In [15]:
print(np.random.choice(7,5)) # uniform  distirbution with replacement means(a  random 5  number will be choosen from 0 to 6 where 7 is 
                            # exclusive and with  replacement mean's there can be repetition

[2 2 1 5 2]


In [18]:
print(np.random.choice(7,5,replace=False))  # same thing  happening as above  the  difference is there is no replacement 

[2 5 6 1 0]


In [20]:
print(np.random.choice(7,5,p=[0.1,0.2,0,0.2,0.4,0,0.1]))

[6 4 3 4 3]


In [21]:
print(np.random.choice(7,5,p=[0.1,0.2,0,0.2,0.4,0,0.1],replace=False))

[4 3 1 6 0]


In [22]:
 # create a 4x4 array with random values. Create an array from the said array swapping first and last rows.

In [46]:
l=np.random.rand(4,4)

In [47]:
l

array([[0.89977262, 0.30895331, 0.70846117, 0.55865405],
       [0.32061787, 0.04484752, 0.27340273, 0.91643122],
       [0.5614796 , 0.12213067, 0.56300901, 0.39454507],
       [0.53788406, 0.29449138, 0.50623315, 0.64353587]])

In [48]:
# so  we  have  to   now  swapp the  first  row and  last row

In [49]:
t=np.copy(l[0])
l[0]=l[-1]
l[-1]=t

In [52]:
l

array([[0.53788406, 0.29449138, 0.50623315, 0.64353587],
       [0.32061787, 0.04484752, 0.27340273, 0.91643122],
       [0.5614796 , 0.12213067, 0.56300901, 0.39454507],
       [0.89977262, 0.30895331, 0.70846117, 0.55865405]])