In [2]:
import numpy as np

In [2]:
n=np.random.rand(40).reshape(8,5)

In [3]:
n

array([[0.32263672, 0.0702205 , 0.40869822, 0.16963126, 0.63713027],
       [0.17311257, 0.87463486, 0.01478234, 0.83318782, 0.5394909 ],
       [0.18792635, 0.15566783, 0.52299431, 0.89645676, 0.96970767],
       [0.86987149, 0.70805326, 0.5449831 , 0.97798469, 0.55750685],
       [0.5728122 , 0.1266248 , 0.18483417, 0.44846227, 0.22087535],
       [0.25174587, 0.93374023, 0.84947174, 0.04586064, 0.97371157],
       [0.02142111, 0.74588463, 0.66396736, 0.80791851, 0.47064524],
       [0.27997686, 0.52927969, 0.21806218, 0.47068641, 0.50902671]])

In [4]:
b=np.random.rand(1400).reshape(200,7)

In [5]:
b

array([[0.22501861, 0.70947731, 0.39421938, ..., 0.79570897, 0.96736248,
        0.29720201],
       [0.23196212, 0.35755068, 0.35435093, ..., 0.56108534, 0.43020462,
        0.99263655],
       [0.22176532, 0.53879138, 0.35245251, ..., 0.95745408, 0.63352241,
        0.15457371],
       ...,
       [0.94587944, 0.80327193, 0.18756966, ..., 0.45328334, 0.68358679,
        0.36094641],
       [0.93116329, 0.06200375, 0.08258116, ..., 0.67910869, 0.13869868,
        0.75474827],
       [0.0443593 , 0.66055081, 0.57741875, ..., 0.05701227, 0.38582566,
        0.57135475]])

In [6]:
np.random.seed(20)

In [7]:
cbrt = np.cbrt(7)

In [8]:
nd=200

In [9]:
p=cbrt*np.random.randn(10,4)+nd

In [10]:
p

array([[201.6908267 , 200.37467631, 200.68394275, 195.51750123],
       [197.92478992, 201.07066048, 201.79714021, 198.1282331 ],
       [200.96238963, 200.77744291, 200.61875865, 199.05613894],
       [198.48492638, 198.38860811, 197.55239946, 200.47003621],
       [199.91545839, 202.99877319, 202.01069857, 200.77735483],
       [199.67739161, 193.89831807, 202.14273593, 202.54951299],
       [199.53450969, 199.7512602 , 199.79145727, 202.97687757],
       [200.24634413, 196.04606934, 198.30611253, 197.88701546],
       [201.78450912, 203.94032834, 198.21152803, 196.91446071],
       [201.0082481 , 197.03285104, 200.63052763, 197.82590294]])

In [11]:
print(np.random.choice(7,5)) # uniform  distirbution with replacement means(a  random 5  number will be choosen from 0 to 6 where 7 is 
                            # exclusive and with  replacement mean's there can be repetition

[2 2 1 5 2]


In [12]:
print(np.random.choice(7,5,replace=False))  # same thing  happening as above  the  difference is there is no replacement 

[6 3 5 4 2]


In [13]:
print(np.random.choice(7,5,p=[0.1,0.2,0,0.2,0.4,0,0.1]))

[6 1 6 0 1]


In [14]:
print(np.random.choice(7,5,p=[0.1,0.2,0,0.2,0.4,0,0.1],replace=False))

[1 6 4 3 0]


In [15]:
 # create a 4x4 array with random values. Create an array from the said array swapping first and last rows.

In [16]:
l=np.random.rand(4,4)

In [17]:
l

array([[0.33533569, 0.70095242, 0.63395338, 0.38189399],
       [0.89902852, 0.40013986, 0.36056156, 0.82452325],
       [0.04793234, 0.71622117, 0.10118238, 0.96626439],
       [0.1964783 , 0.80990096, 0.29555263, 0.55271805]])

In [18]:
# so  we  have  to   now  swapp the  first  row and  last row

In [19]:
t=np.copy(l[0])
l[0]=l[-1]
l[-1]=t

In [20]:
l

array([[0.1964783 , 0.80990096, 0.29555263, 0.55271805],
       [0.89902852, 0.40013986, 0.36056156, 0.82452325],
       [0.04793234, 0.71622117, 0.10118238, 0.96626439],
       [0.33533569, 0.70095242, 0.63395338, 0.38189399]])

In [21]:
l=np.zeros((5,6))

In [22]:
l

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
l[::2,1::2]=5
l[1::2,::2]=6

In [24]:
l

array([[0., 5., 0., 5., 0., 5.],
       [6., 0., 6., 0., 6., 0.],
       [0., 5., 0., 5., 0., 5.],
       [6., 0., 6., 0., 6., 0.],
       [0., 5., 0., 5., 0., 5.]])

In [25]:
k=np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])

In [26]:
# NumPy program to extract all numbers from a given array less and greater than a specified number

In [27]:
n=np.arange(21,81)

In [28]:
n
n.shape

(60,)

In [29]:
l=np.arange(0,24).reshape(4,6)

In [30]:
l.shape

(4, 6)

In [31]:
l

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [32]:
m=16  # number  to  which  greater equal  than and  smaller  equal  we  have  to find

In [33]:
greater=[]
small=[]
for i in range(len(l)):
    for j in range(len(l[i])):
        if np.greater_equal(l[i][j],m):
            greater.append(l[i][j])
        elif np.less_equal(l[i][j],m):
            small.append(l[i][j])
            
            

In [34]:
print(greater)

[16, 17, 18, 19, 20, 21, 22, 23]


In [35]:
print(small)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [36]:
# few   will  think this  is  greatest  one  but  it  is  not   you  must  see   there is always  a simpler way 
# let's  see  

In [37]:
l[l>=m]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [38]:
l[l<=m]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [39]:
# Don't  you  get the same  result  the  difference  between them  is  that  been  is used  with  complex  thing to get 
# the  same  result   but you  shoould   know  or  try  both  way   that  will help   you  in  future  in solving  the  complex 
# code

In [40]:
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29],
              [2.62,2.83,3.12]])

In [41]:
t=np.copy(nums[0])
nums[0]=nums[-1]
nums[0]=t
t1=np.copy(nums[1])
nums[1]=nums[2]
nums[2]=t1

In [42]:
nums

array([[5.54, 3.38, 7.99],
       [1.54, 2.39, 9.29],
       [3.54, 8.32, 6.99],
       [2.62, 2.83, 3.12]])

In [43]:
l1=np.copy(l)

In [44]:
l*l1

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]])

In [45]:
print(np.__version__)

1.26.4


In [46]:
l=[12.23, 13.32, 100, 36.32]

In [47]:
k=np.array(l)

In [48]:
k.ndim #for the dimension

1

In [49]:
p=np.arange(2,11)

In [50]:
p.shape

(9,)

In [51]:
p.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [52]:
k=np.arange(2,11)

In [53]:
k

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
k.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [55]:
l=np.zeros(10)

In [56]:
l

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
l[6]=11

In [58]:
l

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [59]:
l=np.arange(4,13)

In [60]:
l

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
l=l[::-1]

In [66]:
l

array([12, 11, 10,  9,  8,  7,  6,  5,  4])

In [67]:
l=np.array([1,2,3,4])

In [68]:
l=l.astype("float32")

In [69]:
l

array([1., 2., 3., 4.], dtype=float32)

In [70]:
print(l)

[1. 2. 3. 4.]


In [8]:
l=np.arange(1,65).reshape(8,8)

In [9]:
l.shape

(8, 8)

In [10]:
l

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [12]:
o=np.zeros((8,8))

In [13]:
o

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
o[::2,1::2]=1
o[1::2,::2]=1

In [17]:
o

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [19]:
l=[2,3,6,8,9,9,]
l=np.array(l)

In [20]:
l

array([2, 3, 6, 8, 9, 9])

In [21]:
# we  can also  use the  asarray() function  to  convert 

In [22]:
# question  how  to   append the  list   to  the  array  !! how  you can  do  this

In [29]:
p=[2,5,6]
l=np.array([41,24,36,24,12])

In [31]:
j=np.append(l,p,axis=0)

In [32]:
j

array([41, 24, 36,  2,  5,  6])

In [44]:
p=np.empty((3,4))

In [45]:
p

array([[6.93725451e-310, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.03977794e-312, 1.03977794e-312, 1.23075756e-312,
        1.16709769e-312],
       [1.10343781e-312, 9.76118064e-313, 1.06099790e-312,
        1.90979621e-312]])

In [46]:
l1=np.full((3,3),6)

In [47]:
l1

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [86]:
cel=np.array([2,5,6,8,3,5,24]) # array  containing the celsius  value

In [87]:
fah=np.array([80,76,64,34,11,102])  #Array's conataining the  fahrenheit
fah1=np.array([0, 12, 45.21, 34, 99.91, 32])

In [80]:
# conversion  to  fahrenheit 

In [81]:
f_to_c=np.array(list(map(lambda x : (x-32)*5/9,fah)))

In [82]:
f_to_c

array([ 26.66666667,  24.44444444,  17.77777778,   1.11111111,
       -11.66666667,  38.88888889])

In [88]:
# Celsius  to  fahrenheit

In [83]:
c_to_f=np.array(list(map(lambda x : 9/5*(x)+32,cel)))

In [84]:
c_to_f

array([35.6, 41. , 42.8, 46.4, 37.4, 41. , 75.2])

In [85]:
f_to_c1=np.array(list(map(lambda x : (x-32)*5/9,fah1)))
f_to_c1

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778,   0.        ])

In [89]:
x=np.sqrt([1+0j])

In [90]:
x

array([1.+0.j])

In [91]:
y=np.sqrt([0+1j])

In [92]:
x.real
x.imag

array([0.])

In [94]:
y.real

array([0.70710678])

In [95]:
l=np.arange(2,17)

In [96]:
len(l)

15

In [97]:
l.shape

(15,)

In [102]:
np.byte(l)


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int8)

In [104]:
print("Size of the  array",l.size)   

Size of the  array 15


In [105]:
print("Size of the  arrayelement in bytes",l.itemsize)

Size of the  array in bytes 8


In [106]:
print("Total bytes consumed  by the  array",l.nbytes)

Total bytes consumed  by the  array 120


In [107]:
arr=np.array([10,2,40,30,12])

In [108]:
arr1=np.array([40,10])

In [111]:
l=arr1 is  arr

In [112]:
l

False

In [119]:
np.in1d(arr,arr1) # to find  that  this  array is  present in this  one  or  not

array([ True, False,  True, False, False])

In [120]:
np.intersect1d(arr,arr1) # to  find  the  common  between  two arrays

array([10, 40])

In [121]:
#  To find the  set difference  between two array  setdiff1d()

In [123]:
np.setdiff1d(arr,arr1)

array([ 2, 12, 30])

In [124]:
np.union1d(arr,arr1)

array([ 2, 10, 12, 30, 40])

In [131]:
i=np.array([['01' ' V ' 'Debby Pramod' ' 30.21'],
['02' ' V ' 'Artemiy Ellie' ' 29.32'],
['03' ' V ' 'Baptist Kamal' ' 31.0'],
['04' ' V ' 'Lavanya Davide' ' 30.22'],
['05' ' V ' 'Fulton Antwan' ' 30.21'],
['06' ' V ' 'Euanthe Sandeep' ' 31.0'],
['07' ' V ' 'Endzela Sanda' ' 32.0'],
['08' ' V ' 'Victoire Waman' ' 29.21'],
['09' ' V ' 'Briar Nur' ' 30.0'],
['10' ' V ' 'Rose Lykos' ' 32.0']])

In [132]:
i

array([['01 V Debby Pramod 30.21'],
       ['02 V Artemiy Ellie 29.32'],
       ['03 V Baptist Kamal 31.0'],
       ['04 V Lavanya Davide 30.22'],
       ['05 V Fulton Antwan 30.21'],
       ['06 V Euanthe Sandeep 31.0'],
       ['07 V Endzela Sanda 32.0'],
       ['08 V Victoire Waman 29.21'],
       ['09 V Briar Nur 30.0'],
       ['10 V Rose Lykos 32.0']], dtype='<U25')

In [133]:
i.shape

(10, 1)

In [134]:
i.ndim

2

In [2]:
import numpy as np

In [3]:
l=np.array([2,5,0,1,2,0,5,0])

In [4]:
np.all(l)

False

In [6]:
l=np.array([1,2,3])

In [7]:
np.tile(l,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [9]:
# tile helps in  repeating the  array

In [10]:
# repeats  help  in  repeating the element of  the array

In [11]:
np.repeat(l,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [15]:
np.max(l)

3

In [16]:
np.min(l)

1

In [18]:
k=np.array([1,2,3,7,5,6])

In [20]:
# to find  the   indices  of the  maximum  and minimum  value we used  argmax() function 
np.argmax(k)

3

In [21]:
np.argmin(k)

0

In [22]:
a=np.array([1,2])

In [23]:
b=np.array([4,5])

In [24]:
np.greater(a,b)

array([False, False])

In [25]:
np.less(a,b)

array([ True,  True])

In [26]:
np.greater_equal(a,b)

array([False, False])

In [27]:
np.less_equal(a,b)

array([ True,  True])