In [2]:
import numpy as np

In [3]:
n=np.zeros(10)
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
n1=np.ones(10)
n1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
n2=np.ones(10)*5
n2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
l=np.arange(30,71)
# for even one we have  
l=np.arange(30,71,2)

In [7]:
l

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [8]:
ide=np.eye(3,3)

In [9]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
r=np.random.rand(10)

In [11]:
r

array([0.06902399, 0.68260647, 0.09096882, 0.97169943, 0.92469414,
       0.0756574 , 0.47517316, 0.77934428, 0.56107657, 0.049286  ])

In [12]:
no=np.random.normal(0,1,15)

In [13]:
no

array([-0.52978526, -0.02088357, -0.91799913, -0.10754346,  0.66180031,
        2.27114517, -0.74735489, -0.66448757,  0.14198654,  0.97895074,
        0.62437877,  0.02641179, -1.5431499 ,  0.33684708, -0.79856785])

In [14]:
v=np.arange(15,56)

In [15]:
v #original list

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [16]:
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [17]:
# create a 3X4 array and iterate over it.

In [18]:
n=np.arange(1,13)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
n.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
for i in np.nditer(n):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [21]:
v1=np.linspace(5,51,10)

In [22]:
v1

array([ 5.        , 10.11111111, 15.22222222, 20.33333333, 25.44444444,
       30.55555556, 35.66666667, 40.77777778, 45.88888889, 51.        ])

In [23]:
x=np.arange(21)

In [24]:
x[(x>=9) & (x<=15)]*=-1

In [25]:
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [26]:
pok=np.random.randint(0,11,5)

In [27]:
pok

array([6, 0, 5, 4, 7])

In [28]:
# multiply two given  vectors  = [simply an array of 1d ]

# but one thing you must  keep in mind like  both  shapes  must be  same  then only it  can be done

In [29]:
v=np.arange(11,31)
v.shape

(20,)

In [30]:
v1=np.arange(44,64)
v1.shape

(20,)

In [31]:
v*v1

array([ 484,  540,  598,  658,  720,  784,  850,  918,  988, 1060, 1134,
       1210, 1288, 1368, 1450, 1534, 1620, 1708, 1798, 1890])

In [32]:
k=np.arange(10,22)
k=k.reshape(3,4)

In [33]:
k.shape #shape is  used  to  present the  rows  and  columns in the  matrix

(3, 4)

In [34]:
o=np.ones((10,10))

In [35]:
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
o[1:-1,1:-1]=0

In [37]:
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
# i want  to  say like  in this  you  just  have to  know  basic  thing  that to  select  inner thing we use
# indexing basics like [1:-1] which  selects inner thing 
arr=np.arange(10,34)
print(arr)
print()
print(arr[1:-1])


# Do you  see that  how easily it  selects  the inner thing same thing  we  did  to  make changes in identity matrix
# where we want  all border  to  be  1  and  inner  should  be the  zeros o[1:-1,1:-1]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]


In [39]:
# Create the 3X3  matrix of  zeros  in which  main  diagonal  comprise of  element  as the  1,2,3,4,5,6  

In [40]:
z=np.zeros((3,3))

In [41]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
z=np.diag([1,2,3])

In [43]:
z

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [44]:
fck=np.ones((4,4))
fck

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
fck=np.diag([0,0,0])

In [46]:
fck

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
#  create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
# in which  you  have  to  be  1 on even  one  and 0 on odd 

In [48]:
# let's see
jb=np.zeros((4,4))

In [49]:
jb

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
jb[::2,1::2]=1
jb[1::2,::2]=1

In [51]:
jb

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [52]:
n=np.zeros((4,4))

In [53]:
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
n[0,1]=1
n[0,3]=1
n[1,0]=1
n[1,2]=1
n[2,1]=1
n[2,3]=1
n[3,0]=1
n[3,2]=1

# i did  same  thing as  done  earlier  but   what i  have  done  currently is  also  a  way  you can say one of the dumbest
# one  the  wone  above is  of  just  2 line thing  has  been  done  mean's  you  understand  better how  it works

In [55]:
n

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [56]:
k=np.random.random((3,3,3))

In [57]:
k

array([[[0.25626872, 0.5898168 , 0.71803316],
        [0.32957963, 0.65946402, 0.25073732],
        [0.13493761, 0.33510246, 0.36935041]],

       [[0.36627909, 0.10297219, 0.77957794],
        [0.47823704, 0.02181142, 0.68990514],
        [0.1499682 , 0.72024155, 0.75535367]],

       [[0.03236614, 0.34321482, 0.49531092],
        [0.68295531, 0.77407045, 0.21901032],
        [0.478184  , 0.49109325, 0.95703567]]])

In [58]:
sum(k)

array([[0.65491395, 1.03600381, 1.99292202],
       [1.49077198, 1.45534589, 1.15965278],
       [0.76308981, 1.54643727, 2.08173975]])

In [59]:
n=np.random.randn(3,3)

In [60]:
n

array([[ 0.47339192,  0.01953992, -1.41265645],
       [-0.95379544, -0.72810026,  0.33420075],
       [ 1.54420988,  0.53982823,  0.06302036]])

In [61]:
sum(n)

array([ 1.06380635, -0.16873211, -1.01543533])

In [62]:
k=sum(n)
sum(k)

-0.12036109040385412

In [63]:
l=np.sum(n)
l # here we can  do same  thing  with  this  function  but you  should  no other  way also

-0.12036109040385407

In [64]:
np.sum(n,axis=0)

array([ 1.06380635, -0.16873211, -1.01543533])

In [65]:
np.sum(n,axis=1)

array([-0.91972461, -1.34769495,  2.14705847])

In [66]:
c=np.arange(11,24)
c1=np.arange(31,44)

In [67]:
c

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [68]:
c1

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [69]:
n=c[1:-1]*c1[1:-1]

In [70]:
n

array([384, 429, 476, 525, 576, 629, 684, 741, 800, 861, 924])

In [71]:
# we  have  to  find the  dot  product 

In [72]:
np.dot(c,c1) # so here you got  the  value 

8359

In [83]:
l=np.arange(11,23)
l.shape

(12,)

In [84]:
l = np.reshape(l, (4, -1))  

In [85]:
l

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [86]:
v=np.array([1,2,3])

In [87]:
result=np.empty_like(l)

In [88]:
for i in range(4):
    result[i,:]=l[i,:]+v

In [89]:
result

array([[12, 14, 16],
       [15, 17, 19],
       [18, 20, 22],
       [21, 23, 25]])