# Mean Median Mode

In [44]:
# mean: the  average value
# median: the middle value
# mode: the most common value

In [45]:
import numpy as np

In [46]:
x=np.array([1,2,3,4,5,6,7,8,9,10,2,1,3,5,6,8,6])

In [47]:
np.mean(x)

5.0588235294117645

In [48]:
# now  let;s  calculcate the median now but  for that we need  to  sort the array
# first

In [49]:
c=np.sort(x)
c

array([ 1,  1,  2,  2,  3,  3,  4,  5,  5,  6,  6,  6,  7,  8,  8,  9, 10])

In [50]:
np.median(c)

5.0

In [51]:
from scipy import stats
stats.mode(x)

ModeResult(mode=6, count=3)

In [52]:
# Lets; check the  standard deviation

In [53]:
np.std(x)

2.710992616894803

# numpy.arange() numpy.linspace()

In [54]:
# arange() is one  of the  array creation routiness based on numerical ranges.

In [55]:
array=np.arange(1,11)

In [56]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
a=np.arange(0,11,2)

In [58]:
a

array([ 0,  2,  4,  6,  8, 10])

In [59]:
# Linspace

In [60]:
# it returns evenly spaced points or element between the start  and stop valurs

In [61]:
# syntax=np.linspace(start,stop,no. of element/points required)

In [62]:
ar=np.linspace(0,5,10)

In [63]:
ar

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [64]:
ass=np.linspace(0,1,100)

In [65]:
ass

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [66]:
k=np.linspace(0,6,50)

In [67]:
k

array([0.        , 0.12244898, 0.24489796, 0.36734694, 0.48979592,
       0.6122449 , 0.73469388, 0.85714286, 0.97959184, 1.10204082,
       1.2244898 , 1.34693878, 1.46938776, 1.59183673, 1.71428571,
       1.83673469, 1.95918367, 2.08163265, 2.20408163, 2.32653061,
       2.44897959, 2.57142857, 2.69387755, 2.81632653, 2.93877551,
       3.06122449, 3.18367347, 3.30612245, 3.42857143, 3.55102041,
       3.67346939, 3.79591837, 3.91836735, 4.04081633, 4.16326531,
       4.28571429, 4.40816327, 4.53061224, 4.65306122, 4.7755102 ,
       4.89795918, 5.02040816, 5.14285714, 5.26530612, 5.3877551 ,
       5.51020408, 5.63265306, 5.75510204, 5.87755102, 6.        ])

# Zeros  and identity in numpy

In [68]:
ar=np.zeros((3,4))

In [69]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
ar1=np.zeros(5)

In [71]:
ar1

array([0., 0., 0., 0., 0.])

In [72]:
# ones

In [73]:
an=np.ones(5)

In [74]:
an

array([1., 1., 1., 1., 1.])

In [75]:
an1=np.ones((5,7))

In [76]:
# identity matrix -  matrix in which diagonals are of one's

In [77]:
tu=np.eye(5)

In [78]:
tu

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random Numbers

In [88]:
x=np.random.rand()

In [89]:
x

0.5760078963778473

In [90]:
from  numpy  import random

In [91]:
s=random.rand()

In [92]:
s

0.6852101510461479

In [93]:
x=random.rand(0,1)

In [94]:
x

array([], shape=(0, 1), dtype=float64)

In [95]:
# Rand() method 

In [96]:
# IT returns the  random samples  of type  float between 0 and 1

In [97]:
# samples are taken from a uniform distirbution

In [98]:
d=np.random.rand(5)

In [99]:
d

array([0.75687462, 0.28693183, 0.32231649, 0.23409232, 0.78628089])

In [100]:
# now let's create  a matrix 
x=np.random.rand(5,5)

In [101]:
x

array([[0.52595494, 0.45262636, 0.57221572, 0.21186991, 0.19768573],
       [0.99090348, 0.42231338, 0.78499079, 0.55360144, 0.93674402],
       [0.33029054, 0.69525153, 0.00774526, 0.35497826, 0.46161205],
       [0.50716176, 0.31729462, 0.22093384, 0.52643949, 0.46167783],
       [0.06999815, 0.51421579, 0.3855705 , 0.14395938, 0.89640387]])

In [102]:
# Randn()

In [103]:
# note that  it fills the  array with  random floats sampled from a univariate
# normal(gausian) distirbution of mean  and variance 

In [104]:
# note that normal  distirbution is  a distirbution which is continous in nature and 
# has a pdf or  probabillity density function

In [105]:
# if we provide no argument then a single float  randomly sampled from the 
# distirbution is returned

In [106]:
# No argument
x=np.random.randn()

In [107]:
x

-0.10237974573249019

In [108]:
# 1 d array
x=np.random.randn(5)
x

array([-0.51611153,  0.2519805 , -0.57147544, -0.30364214, -2.47545409])

In [110]:
# 2d array or matrix
c=random.randn(4,3)
c

array([[ 1.46700709, -0.14962303, -2.06168288],
       [ 0.20826601,  0.71103406, -2.02724905],
       [ 0.64743724,  0.2840004 , -0.00711759],
       [ 0.99590853,  1.53508018,  1.4462483 ]])

In [112]:
# 3d array
k=random.randn(2,3,3)
k

array([[[-0.31317589,  0.53961203,  0.14384747],
        [-0.75582328,  0.86596792, -0.37892055],
        [-1.82777747,  1.30846417,  0.5929075 ]],

       [[ 1.231724  , -1.50471821,  0.52116789],
        [-1.23521185, -0.72947504, -1.04696148],
        [-0.79340918,  0.62212057,  0.36960856]]])

In [113]:
# randint() is an  inbuilt function of the  random module of numpy 
# the  module  give  aces to various  useful  functions and one of them able to 
# generate random numbers,which is randint()

In [114]:
# SYNTAX: np.random.randint(start,stop)

In [115]:
# note that bothe  start and  stop  values must be  integer values

In [120]:
c=np.random.randint(1,10)

In [121]:
c

9

In [123]:
# generate  a ranoom number between  -10 and -1

In [124]:
x=np.random.randint(-10,-1)

In [125]:
x

-5

In [131]:
# Let's see what  happens when we pass non integer values
l=np.random.randint(1.322,2.111)

In [132]:
l

1

In [133]:
# I am  assuring  u that  whenever  you  try  to  pass the  non integer  number then 
# it will always  take it  as the  integer

In [134]:
k=np.random.randint(-5,4)

In [135]:
k

-2

In [137]:
arr=np.random.randint(1,10000,size=1000)
arr

array([7064, 3848, 9866, 4726, 7601, 2910,   95, 9474, 9140, 2594,  378,
        878, 5857, 7150, 8467,  507, 2940, 2245, 4467, 5384, 3937, 7796,
       1821, 3674, 2238, 9706,  615, 7493, 8094, 8979, 4916, 6523, 8574,
        645, 5601, 3432, 7249,  907, 1824, 1627, 1370,   72, 3228, 7587,
       5786, 3742, 5881,  607, 5310, 6544, 8161,  481, 1548, 1825, 7996,
        360, 2987, 1384, 8030, 5596, 7252, 9714,  590, 8893, 5494, 1180,
       9207,  722,  292, 1427,  116, 5745, 8428, 1603, 6989, 8781, 6641,
       3863, 7325, 4975, 1971, 5588, 5851, 3080, 7314,  439, 9186, 5004,
       1992, 2227, 8476, 3354, 8697, 3900, 1549, 1271, 4894, 1527, 5141,
       9794, 1662, 9239, 1965, 6513, 3837, 2436, 9254, 3750, 4527, 4707,
       5335,  441,  197, 7601, 8781, 6736, 9555, 7430,  832,  486, 6407,
       4375, 3786,  756, 8472, 7936, 6259, 9607, 9466, 9526,  724, 4078,
       7134, 1665, 5548, 6621,  211, 6671, 8776, 8437, 1096, 4663, 7052,
       4960, 1909,  264, 5664, 3125, 9664, 5498, 53

In [138]:
min_=min(arr)

In [139]:
min_

2

In [140]:
max_=max(arr)

In [141]:
max_

9994

In [142]:
arrmean=np.mean(arr)

In [143]:
arrmean

4960.208

In [144]:
# a  random  permutation refers to  an  arrangement  of  elements
# for  example  [4,3,2,1] is  a  random  permutation of the  [1,2,3,4]
# a lot  of  other permutation is possible  as well but we get only 1

In [149]:
# method 1 
arr=np.array([1,2,3,4,5,6])
k=np.random.shuffle(arr)
print(k)

None


In [148]:
print(arr)

[6 1 4 5 3 2]


In [150]:
# so  here  you'll see that  shuffle  modifies the  original array that's  why it didn't
# show anything in the  k

In [155]:
# method2 permutation method
arr1=np.array([1,2,3,4,5,6,7])
f=np.random.permutation(arr)

In [156]:
f

array([2, 1, 4, 6, 5, 3])

In [157]:
# so here you'll see the  f  with  changed (shuffled)

In [159]:
print(arr1)

[1 2 3 4 5 6 7]


In [160]:
# there is no  change in the  original  array  

In [161]:
# # i think you got  everything i think you  may got it well
# shuffle() - to make changes to  original  array
# permutation () -if you  dont want  any changes in the original  array