In [3]:
import  numpy  as np

In [4]:
arr=np.array([1,2,3,4,5,6,7])

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.size

7

In [8]:
sd=np.array([[2,5,8],[4,2,1]])
sd.size

6

In [9]:
sd

array([[2, 5, 8],
       [4, 2, 1]])

In [10]:
n=np.array([[[2,5,8],[8,2,8]],[[2,12,6],[4,7,5]]])
print(n.shape)
print(n)
n.ndim


(2, 2, 3)
[[[ 2  5  8]
  [ 8  2  8]]

 [[ 2 12  6]
  [ 4  7  5]]]


3

In [11]:
n1=np.array([[[[2,5,8],[8,2,8]],[[2,12,6],[4,7,5]],[[2,5,8],[8,2,8]],[[2,12,6],[4,7,5]]]])
print(n1.shape)
print(n1)
n1.ndim


(1, 4, 2, 3)
[[[[ 2  5  8]
   [ 8  2  8]]

  [[ 2 12  6]
   [ 4  7  5]]

  [[ 2  5  8]
   [ 8  2  8]]

  [[ 2 12  6]
   [ 4  7  5]]]]


4

In [12]:
s=np.array([[[1,2,3,4],[2,3,5,8]],[[5,14,47,15],[7,1,2,6]]])
s.ndim
s.size

16

In [13]:
s1=s.reshape(2,2,2,2)
s1.ndim

4

In [14]:
s1[0:4]

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 2,  3],
         [ 5,  8]]],


       [[[ 5, 14],
         [47, 15]],

        [[ 7,  1],
         [ 2,  6]]]])

In [15]:
# operation  performed on  array

In [16]:
s1

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 2,  3],
         [ 5,  8]]],


       [[[ 5, 14],
         [47, 15]],

        [[ 7,  1],
         [ 2,  6]]]])

In [17]:
# Multiplication
s1[0]*s1[1]

array([[[  5,  28],
        [141,  60]],

       [[ 14,   3],
        [ 10,  48]]])

In [18]:
# Subtraction
s1[1]-s1[0]

array([[[ 4, 12],
        [44, 11]],

       [[ 5, -2],
        [-3, -2]]])

In [19]:
# Now on 3d  array

In [20]:
n

array([[[ 2,  5,  8],
        [ 8,  2,  8]],

       [[ 2, 12,  6],
        [ 4,  7,  5]]])

In [21]:
n[0]*n[1]

array([[ 4, 60, 48],
       [32, 14, 40]])

In [22]:
# here  one thing  to  do  like  to  print the  last element from the  last row

In [23]:
s1

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 2,  3],
         [ 5,  8]]],


       [[[ 5, 14],
         [47, 15]],

        [[ 7,  1],
         [ 2,  6]]]])

In [24]:
s1[1,1,1,1]  #or s1[1][1][1][1]

6

In [25]:
arr=np.array([[1,2,7,4],[2,4,3,1]])

In [26]:
# Second row  and  last element
arr[1][-1]

1

In [27]:
print(arr)

[[1 2 7 4]
 [2 4 3 1]]


In [28]:
# Second row and  last element 
arr[1,-2]

3

In [29]:
# First  row  and  second  last element
arr[0,-2] # or arr[-2,-2]

7

In [30]:
arr1=np.array([1,2,3,4,5,6,7,8,9])

In [31]:
arr1[0:4:2]

array([1, 3])

In [32]:
  # DAtatype

# i-integer
# u-unsigned integer
# S-String
# f-float
# c-complex float
# m- timedata
# M - datetime
# O-object
# V-fixed chunk of memory./void

In [33]:
arr=np.array([5,2,7,5],dtype="i4")
arr

array([5, 2, 7, 5], dtype=int32)

In [34]:
# Converting  datatype (Astype)

In [35]:
arr=np.array([1.1,2.1,3.1])

In [36]:
new=arr.astype('i')

In [39]:
arr.dtype

dtype('float64')

In [38]:
new

array([1, 2, 3], dtype=int32)

In [40]:
srr=np.array([1,0,3,0,1])

In [43]:
o=srr.astype('bool')

In [44]:
o

array([ True, False,  True, False,  True])