In [2]:
import  numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
print(np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140551260102944
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    versio

In [5]:
# to check whethere all element of the  array is the  zero or  not

In [6]:
x=np.array([1,2,3,4,5])

In [7]:
print("Original Array")

Original Array


In [8]:
np.all(x)

True

In [9]:
c=np.array([2,0,4,6,8])

In [10]:
np.all(c)

False

In [11]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [12]:
np.add(1.0,4.0)

5.0

In [13]:
x1=np.arange(9.0)

In [14]:
x1

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [19]:
x1=x1.reshape((3,3))

In [20]:
x2=np.arange(3.0)

In [21]:
x2

array([0., 1., 2.])

In [22]:
s=np.add(x1,x2)

In [23]:
s

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [31]:
# to check none (all) of the element of array is zero then  we check through 
# np.all()

In [32]:
# to check  whethere any element is  zero  or not 
# np.any()

In [29]:
s=np.array([1,0,2,5])

In [30]:
np.all(s)

False

In [33]:
s=np.array([1,4,2,5])

In [34]:
np.all(s)

True

In [35]:
x=np.array([1,0,0,0]) # any() is used to  check 

In [36]:
np.any(x)

True

In [37]:
c1=np.array([0,0,0,0]) 

In [39]:
np.any(c1) #here it gives False because there is no element other than 0

False

In [41]:
# ALways remember any() - is used to check that  is there any element other than 0(non-zero

In [42]:
# and all()  is used to check whether there is  any element which  is zero

In [43]:
# all() -True - [1,2,3,5]
# any() -True -[1,0,0,2]  

In [44]:
a=np.array([1,0,np.nan,np.inf])

In [45]:
a

array([ 1.,  0., nan, inf])

In [50]:
# to check the element wise for the  finiteness
np.isfinite((a))

array([ True,  True, False, False])

In [51]:
# to  check the  element wise positive and negative infinity
np.isinf((a))

array([False, False, False,  True])

In [52]:
# to check whether element is nan
np.isnan((a))

array([False, False,  True, False])

In [53]:
s=np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

In [54]:
np.iscomplex(s)

array([ True, False, False, False, False,  True])

In [55]:
np.isreal(s)

array([False,  True,  True,  True,  True, False])

In [56]:
np.allclose([1.0,np.nan],[1.0,np.nan])

False

In [58]:
np.allclose([1e10,1e-8],[1.00001e10,1e-9])

True

In [68]:
z=np.array([3,5])

In [66]:
l=np.array([2,5])

In [70]:
z1=np.array([1,5])

In [74]:
# Here term like  less equal,greater_equal  acts between the  two array  
# np.greater_equal(z1,l) -> z1>=l  

In [75]:
np.greater_equal(z1,l)

array([False,  True])

In [76]:
np.greater_equal(z,l)

array([ True,  True])

In [77]:
np.less_equal(z1,l)

array([ True,  True])